import os
import re
import sys
from pathlib import Path

import yaml

sys.path.insert(0, str(Path(__file__).resolve().parent))
import vault_manifest

VAULT = Path(os.environ.get("POKE_VAULT_ROOT", str(Path.home() / "poke-vault"))).resolve()
CANON = vault_manifest.canon_dirs(VAULT)


def fm(path):
    lines = path.read_text(errors="replace").split("\n")
    if not lines or lines[0].strip() != "---":
        return {}
    end = next((i for i in range(1, len(lines)) if lines[i].strip() == "---"), None)
    if end is None:
        return {}
    try:
        m = yaml.safe_load("\n".join(lines[1:end])) or {}
        return m if isinstance(m, dict) else {}
    except Exception:
        return {}


def main():
    by_kind = {k: [] for k in CANON}
    by_tag = {}
    for kind in CANON:
        d = VAULT / kind
        if not d.exists():
            continue
        for p in sorted(d.glob("*.md")):
            m = fm(p)
            rel = f"{kind}/{p.name}"
            title = m.get("title", p.stem)
            status = m.get("status", "")
            by_kind[kind].append((title, rel, status))
            for tag in (m.get("tags") or []):
                by_tag.setdefault(str(tag), []).append((title, rel))

    lines = ["# Vault Index", "", "_Generated by gen_index.py — do not hand-edit._", ""]
    for kind in CANON:
        items = by_kind[kind]
        if not items:
            continue
        lines.append(f"## {kind} ({len(items)})")
        for title, rel, status in items:
            suffix = f" — {status}" if status else ""
            lines.append(f"- [{title}]({rel}){suffix}")
        lines.append("")
    if by_tag:
        lines.append("## By tag")
        for tag in sorted(by_tag):
            refs = ", ".join(f"[{t}]({r})" for t, r in by_tag[tag])
            lines.append(f"- **{tag}**: {refs}")
        lines.append("")

    (VAULT / "index.md").write_text("\n".join(lines))
    print(f"wrote {VAULT/'index.md'} ({sum(len(v) for v in by_kind.values())} cards, {len(by_tag)} tags)")


if __name__ == "__main__":
    main()
